### ISSUE TITLE
Slider on Windows 10

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#77] opened 2016-02-11 18:10 UTC
The plot slider is broken on some Windows 10 browsers. Reimplement with a proper angular widget.

**Comment by mrakitin** [comment] 2016-02-23 22:26
It looks to be a duplicate of https://github.com/radiasoft/sirepo/issues/59.

**Comment by mrakitin** [comment] 2016-02-23 22:43
It works now in both Firefox and Chrome browsers on Windows 10.

**Comment by mrakitin** [comment] 2016-03-29 19:54
Closing as a duplicate.

**Closed by mrakitin** 2016-03-29 19:54 UTC
