### ISSUE TITLE
Sirepo/Elegant Extension request 

### ISSUE THREAD

**Issue by smlund** [radiasoft/sirepo#1975] opened 2019-10-24 19:01 UTC
Please consider generalizing interface to: 
1) Open multiple plot windows in each category under the visualization tab.  For example, moments for rms beam size in x and y (plot reading run_setup.sigma) may be desired in one plot and then in a 2nd window with correlated dispersive moments (different units and scales) is desirable to plot reading this same data output file.  Students need to look at such quantities simultaneously in a variety of lattices.  
2) The pull down menus in plots under visulalization need to have keys defined.  How are we supposed to know that "Sx" is x-sigma with centroid subtracted.  Emittances have many defs also.  There needs to be more.  I am not even sure if these names correspond to Elegant manual names.  

This would help students get started. 

Thanks! Steve 

Professor Steven M. Lund 
Director, US Particle Accelerator School / FNAL 
Michigan State University / FRIB
517-908-7291 
lund@frib.msu.edu

**Comment by bruhwiler** [comment] 2019-10-25 20:52
Thanks for the great feedback @smlund 

In the future, it would be helpful if you could limit each new issue to a single bug or a single feature request.

Regarding point 1) Open multiple plot windows in each category under the visualization tab --

This is an excellent suggestion. It has come up multiple times over the past couple of years.
I thought we already had a GitHub issue documenting this, but I cannot find it. I'm not sure how much work it will be to implement.

@moellep -- the idea is simply to enable users to clone any report on the visualization tab.

Regarding point 2)  The pull down menus in plots under visualization need to have keys defined --

I agree that some of the variable names are unconventional, but I'm sure they are being taken from the elegant-generated SDDS files and were not invented by RadiaSoft.  I'll discuss with @moellep to come up with some ways of improving the situation.

**Comment by moellep** [comment] 2019-10-25 21:43
#965 is the issue to allow duplicating a report. The webcon app has this feature and it could be generalized for the other apps.

The column names come directly from the elegant SDDS output files. The files do include a description for some fields which might be helpful. For example, Sx has the description "sqrt(x-<x>)^2)". We could show these values next to the column name.

**Comment by smlund** [comment] 2019-10-26 00:33
Anything extra would help.  But even in Sx what you write is not quite right since it appears to have centeroid subtracted in the moment.  But the x in the phase-space plots does not (plots shift with centeroid).   A lot of the quantities in the drop down menus are hard to even guess.  It would be best if, in addition to short descriptions, that you also have links to the relevant part in the Elegant Manual if Borland would let you embed such so you don’t have a document maintenance nightmare.

**Comment by robnagler** [comment] 2022-02-21 21:58
Sort of a duplicate of #878

**Closed by robnagler** 2022-02-21 21:58 UTC
Labels: enhancement, 2, customer
