### ISSUE TITLE
server error page is too disruptive

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2108] opened 2019-12-11 21:52 UTC
Currently when something unexpected happens on the server, the app gets redirected to /app/#error

The error page doesn't provide any indication on how to get back to the simulation, and has no simulation id present.

I think it would be better for these errors to route back to the report which caused the problem, if possible. For example, the frame server error from #2107 would show up as "server error" or something appropriate in the report window, rather than redirecting out of the app.

The underlying codes can fail in many unexpected ways, so showing a server error on the report, rather than kicking out of the app would be better for users and developers.

**Comment by robnagler** [comment] 2019-12-11 22:55
Duplicate of https://github.com/radiasoft/sirepo/issues/2069?

**Comment by moellep** [comment] 2019-12-11 22:57
Yes, with the addition of showing the failure in the report window if possible.

**Closed** 2019-12-17 16:29 UTC
