### ISSUE TITLE
Unexpected Error - Something Up with the elements?

### ISSUE THREAD

**Issue by MikiMiller** [radiasoft/sirepo#1022] opened 2018-01-17 20:32 UTC
https://uspas-sirepo.radiasoft.org/elegant#/visualization/QhYIPvHO

https://uspas-sirepo.radiasoft.org/elegant#/lattice/QhYIPvHO

**Comment by robnagler** [comment] 2018-01-17 20:45
Might be related to:

```text
Jan 17 20:38:47   212 47833 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py:282:_find_job Os7a9CfS-QhYIPvHO-animation: job not found; len_jobs=4
```

**Comment by robnagler** [comment] 2018-01-17 20:45
and this:

```text
Jan 17 20:38:50   212 15133 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py:270:race_condition_reap RpAoLc10-6myfpQe9-animation: aborting and deleting job; tid=98bdccc0-e4d1-453a-bacb-9980108bacc2 celery_state=PENDING
Jan 17 20:38:51   212 40367 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py:298:_find_job LmmCZ2I3-gJ1KSivR-bunchReport1: deleted errant or ready job; tid=39711906-9664-4702-a89a-65255d6ca4d3 ready=True
Jan 17 20:38:51   212 84779 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py:282:_find_job mMeH7Unk-tG299QR8-bunchReport1: job not found; len_jobs=5
```

**Comment by robnagler** [comment] 2018-01-17 23:07
It's likely that this is caused by no beamline. The elegant error is "Please remove concat_order from run_setup". The simulation gets in status = error, but it doesn't seem to get that status back to the client.

**Comment by robnagler** [comment] 2019-12-09 17:36
Can we close this?

**Comment by bruhwiler** [comment] 2019-12-09 17:39
Yes. Closing now.

**Closed by bruhwiler** 2019-12-09 17:39 UTC
Labels: customer
