### ISSUE TITLE
Alpha Release 2022-05-17 16:31:05 UTC

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4409] opened 2022-05-13 18:43 UTC
- 4386 flash improvements radiasoft/sirepo#4416

**Comment by moellep** [comment] 2022-05-17 16:54
Alpha is failing due to the feature_config_test.py failure:
```
tests/feature_config_test.py::test_1 FAILED
...
pykern.pkunit.PKFail: tests/feature_config_test.py:24:test_1 Exception was not raised: expecting=xyz.*proprietary_sim_types
```
This test doesn't fail on dev.

**Comment by moellep** [comment] 2022-05-17 17:20
I can reproduce it on dev with the latest pykern now.

**Comment by moellep** [comment] 2022-05-17 17:38
Fixed with https://github.com/radiasoft/pykern/pull/173

**Closed** 2022-05-17 19:15 UTC
Labels: release
