### ISSUE TITLE
20230109 discard changes fails for angularjs on prod for react apps

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5342] opened 2023-01-09 18:05 UTC
Discard changes to example is broken for jspec/genesis/warppba on production in the angularjs app.

**Comment by robnagler** [comment] 2023-01-09 18:07
I think this is why we should add new APIs for React.

**Comment by garsuga** [comment] 2023-01-09 23:50
Are the react_sim_types still defined in production? Do we need to check an additional value when seeing if an app should be treated differently? Is there any output I can access from these errors?

**Comment by garsuga** [comment] 2023-01-09 23:54
> I think this is why we should add new APIs for React.

I am not sure this will prevent future issues. The fix from login where a special case was added to local routes to give React routes is an example of where a separate API would not have any effect. I checked the changes made in the login PR and they should all be behind the statement `if simulation_type in sirepo.feature_config.cfg().react_sim_types:`. Is this check not enough for how production is configured? Do we also need to check if `react_server` is defined?

**Comment by moellep** [comment] 2023-01-10 00:03
Yes, I think setting react_sim_types=[] in feature_config is the right choice, or only setting that value on dev.

**Comment by garsuga** [comment] 2023-01-10 00:44
Yes but if that is the expectation then we should also have a check for `assert react_sim_types=[] or react_server is not None` to make sure there is not another edge case where React has sim_types but is not proxying.

**Comment by robnagler** [comment] 2023-01-10 13:50
r = sim_type in _cfg.react_sim_types
I see some of the problems. In sirepo.uri, there's:

```py
_cfg = sirepo.feature_config.cfg()
```

This should not be cached globally. It could be cached in the function:

```py
```

But that's unnecessary

**Comment by robnagler** [comment] 2023-01-10 14:20
Discard changes is broken, because it is not a new API for React. This is the broken code:

```tsx
    let discardChanges = async () => {
        let { simulationId, models: { simulation: { name }} } = simulationInfo || await simulationInfoPromise;
        await deleteSimulationPromise(simulationId);
        let newSimulationInfo: SimulationInfoRaw = await (await fetch(`/find-by-name-auth/${appName}/default/${name}`)).json();
        console.log("simulationInfo", newSimulationInfo);
        navigate(`/${appName}/${newSimulationInfo.models.simulation.simulationId}`);
    }
```

because this code is broken:

```js
    self.revertToOriginal = function(applicationMode, name) {
        if (! appState.isLoaded()) {
            return;
        }
        appState.deleteSimulation(
            appState.models.simulation.simulationId,
            function() {
                requestSender.globalRedirect(
                    'findByNameWithAuth',
                    {
                        '<simulation_name>': name,
                        '<simulation_type>': SIREPO.APP_SCHEMA.simulationType,
                        '<application_mode>': applicationMode,
                    }
                );
            }
        );
    };
```

findByNameWithAuth is not a published API. It was designed with a very specific purpose (redirecting to the app from a published findByName URL). Discard changes should not have used it. React should not have copied this code, because this is the problem with copying code that's incorrect which we've known is incorrect since 2019 #1972.

The proper fix for this is to create api_revertExample, which would reset the state of the simulation and return the simulationData which the React app would then update its state with, just like if there was an update collision. We should be able to handle those without having to refresh the entire app as is done in angular.

In the mean time, all changes to sirepo.uri and sirepo.server (others?) should be reverted to fix this particular problem. React can be broken since it's only on dev.

**Closed** 2023-01-10 19:44 UTC
