### ISSUE TITLE
SRW plots need to modify title & legend when plot type is changed

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#190] opened 2016-05-10 20:10 UTC
The screenshot below sows the problem.
The plot type has been changed to Re(E) but the title and the legend still say 'Intensity'

![image](https://cloud.githubusercontent.com/assets/3825435/15160855/e972cb12-16b8-11e6-8081-75cb07e4878f.png)

**Comment by mrakitin** [comment] 2017-01-10 19:50
Duplicate of #76.

**Closed by mrakitin** 2017-01-10 19:50 UTC
Labels: bug
