### ISSUE TITLE
SRW: error message upon requesting Export ML Script for TES

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#3877] opened 2021-10-07 23:15 UTC
I am using this simulation for TES:
https://www.sirepo.com/srw#/beamline/ReJMAvC6

When I select "Export ML Script", I get the following error message
`Application Error: Error: [$compile:multidir] http://errors.angularjs.org/1.7.8/$compile/multidir?p0=numberList&p1=%20(module%3A%20SirepoApp)&p2=numberList&p3=%20(module%3A%20SirepoApp)&p4=new%2Fisolated%20scope&p5=%3Cdiv%20data-number-list%3D%22%22%20data-model%3D%22model%22%20data-field%3D%22model%5Bfield%5D%22%20data-info%3D%22info%22%20data-type%3D%22Float%22%20data-count%3D%22%22%3E. A report was sent to the server.`

**Comment by mkeilman** [comment] 2021-10-08 02:22
Duplicate of #3864, fixed in #3865 (pushed to alpha so far)

**Closed by mkeilman** 2021-10-08 02:22 UTC
