### ISSUE TITLE
Sirepo / Elegant Interface 

### ISSUE THREAD

**Issue by smlund** [radiasoft/sirepo#1979] opened 2019-10-24 19:28 UTC
On using Sirepo/Elegant interface:

I tried running using "divide elements" under the control tab.  This made the twiss output look good and smooth as one would want for students.  However, output plots from run_setup.sigma and run_centup.centroid and others only had initial and final points in unless I went back and segmented elements and put watch points in them.  This seems to defeat the purpose.  For student use, smooth curves are much better that are easy to setup.  Am I mis-setting something or is this some sort of bug.  It is VERY confusing (I am not an elegant user) when one sets up a new run and a plot is showing only initial and final points.  Probably having simple examples setup in a clean manner to get good output could help significantly ... particularly for students.  

Thanks! Steve

Professor Steven M. Lund
Director, US Particle Accelerator School / FNAL
Michigan State University / FRIB
517-908-7291
lund@frib.msu.edu

**Comment by bruhwiler** [comment] 2019-10-25 17:38
I believe this is essentially a duplicate of issue #1983, which is being addressed by the development team.

Hence, I'm closing this issue.

**Closed by bruhwiler** 2019-10-25 17:38 UTC
Labels: 1, customer
