### ISSUE TITLE
SRW - Bug with 2 watchpoints

### ISSUE THREAD

**Issue by DmitrySmalyuk** [radiasoft/sirepo#247] opened 2016-07-27 20:36 UTC
Description: The removal of a single watchpoint (1) from a beamline simulation causes a significant change in the intensity report at another watchpoint (2). Watchpoint (2) is at a higher nominal position than Watchpoint (1). Watchpoint (2) is never moved or removed. No other beamline elements are involved.

How to reproduce:

- create New Simulation

- choose source type Electron Beam with Idealized Undulator

- do not alter any default parameters

- go to Beamline

- drag and drop a watchpoint (1) at nominal position 22m

- drag and drop a watchpoint (2) at nominal position 32m

- save changes. export & save the intensity report at watchpoint (2) at 32m

- remove the watchpoint (1) at 22m 

- save changes. export & save the intensity report at watchpoint (2) at 32m.

- compare the two intensity reports from watchpoint (2) at 32 meters, they will be significantly different, even though it is not reasonably expected for them to be different.

**Comment by moellep** [comment] 2016-07-28 21:15
I've reproduced this, but I don't have an explanation or a fix. The difference between the two cases is the first one starts at op_r=22.0 and propagates the wavefront through the 10m drift and the second case starts at op_r=32.0 with no prior propagation.

**Comment by mrakitin** [comment] 2016-07-28 21:54
Oleg (@ochubar) may have comments on this case.

**Comment by mrakitin** [comment] 2016-08-03 14:36
We had a conversation with Oleg about this issue. The problem is that there were not enough sampling/number of points to show "good" plots due to the additional drift. When the sampling factor increased, the plot became smooth and nice-looking. WAD, closing.

**Closed by mrakitin** 2016-08-03 14:36 UTC
Labels: 1st Priority
