### ISSUE TITLE
Sirepo upload file modal does not respond to errors

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6555] opened 2023-11-29 22:00 UTC
I tried uploading an 800Mb file which is larger than we allow in nginx. nginx responded with a 413 Request Entity Too Large but nothing changed in the modal after this. It continued to look like it was uploading

![Screen Shot 2023-11-29 at 2 55 05 PM](https://github.com/radiasoft/sirepo/assets/10264515/0bb821aa-bafa-416d-b7b3-44c039709e65)

In the case of dev you can trigger this by putting an `assert 0` in sirepo.server.api_uploadFile. 

The modal should respond to errors letting the user know there were problems.

**Comment by moellep** [comment] 2023-11-30 23:08
This is a duplicate of #6134

**Closed** 2024-01-08 21:28 UTC
