### ISSUE TITLE
sirepo failing to start on a clean vm

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4320] opened 2022-04-12 20:29 UTC
Load these two files in v4:
* [run.sh.txt](https://github.com/radiasoft/sirepo/files/8476354/run.sh.txt)
* [Vagrantfile.txt](https://github.com/radiasoft/sirepo/files/8476357/Vagrantfile.txt)

Remove the .txt. Then vssh and then bash /vagrant/run.sh.

![Screen Shot 2022-04-12 at 2 26 31 PM](https://user-images.githubusercontent.com/5495179/163047805-d7fb1cd5-3c49-4974-8827-0ed826ce4211.png)

```txt
10.10.10.1 - - [12/Apr/2022 20:25:21] "GET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 -
../sirepo/auth/__init__.py:398:require_user user not logged in: logged out uid=None
10.10.10.1 - - [12/Apr/2022 20:25:21] "POST /simulation-list HTTP/1.1" 200 -
10.10.10.1 - - [12/Apr/2022 20:25:21] "{"simulationType":"myapp"}GET /static/html/login.html?20220412.202520 HTTP/1.1" 405 -
../sirepo/server.py:144:api_errorLogging 10.10.10.1: javascript error: {
    "cause": "<no cause>",
    "message": "Error: [$templateRequest:tpload] http://errors.angularjs.org/1.7.8/$templateRequest/tpload?p0=%2Fstatic%2Fhtml%2Flogin.html%3F20220412.202520&p1=405&p2=METHOD%20NOT%20ALLOWED",
    "stackTrace": "@http://v4.radia.run:8000/static/js/ext/angular.min.js?20220412.202520:7:173
@http://v4.radia.run:8000/static/js/ext/angular.min.js?20220412.202520:167:308
```

Refresh caused nothing to happen.

Then got this

```txt
10.10.10.1 - - [12/Apr/2022 20:27:16] "GET /static/img/sirepo_animated.gif HTTP/1.1" 304 -
../sirepo/uri_router.py:231:_dispatch exception=400 Bad Request: The browser (or proxy) sent a request that this server could not understand. path=simulation-list stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 229, in _dispatch
    return call_api(route.func, kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 86, in call_api
    r = sirepo.http_reply.gen_exception(e)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_reply.py", line 60, in gen_exception
    return _gen_exception_werkzeug(exc)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_reply.py", line 386, in _gen_exception_werkzeug
    raise exc
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 77, in call_api
    r = flask.make_response(f(**kwargs) if kwargs else f())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 495, in api_listSimulations
    req = http_request.parse_post()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_request.py", line 90, in parse_post
    r = parse_json()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_request.py", line 54, in parse_json
    req.get_data(cache=False),
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/wrappers/request.py", line 405, in get_data
    rv = self.stream.read()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

Exception was printed at:

werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 347, in handle
    super().handle()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 306, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
10.10.10.1 - - [12/Apr/2022 20:27:16] "POST /simulation-list HTTP/1.1" 400 -
```

Then this:

```txt
10.10.10.1 - - [12/Apr/2022 20:29:17] "GET /static/js/sirepo-plotting.js?20220412.202916 HTTP/1.1" 304 -
10.10.10.1 - - [12/Apr/2022 20:29:17] "GET /static/js/sirepo-plotting-vtk.js?20220412.202916 HTTP/1.1" 304 -
10.10.10.1 - - [12/Apr/2022 20:29:17] "GET /static/js/sirepo-common.js?20220412.202916 HTTP/1.1" 304 -
10.10.10.1 - - [12/Apr/2022 20:29:17] "GET /static/js/sirepo-geometry.js?20220412.202916 HTTP/1.1" 304 -
10.10.10.1 - - [12/Apr/2022 20:29:17] "GET /auth-state?20220412.202916 HTTP/1.1" 200 -
```

**Comment by robnagler** [comment] 2022-04-12 20:33
@moellep This is pretty weird. I did get it to work. Note that I updated the initial message, because got submitted too quickly.

**Comment by robnagler** [comment] 2022-04-12 20:34
![Screen Shot 2022-04-12 at 2 34 26 PM](https://user-images.githubusercontent.com/5495179/163049067-c288e62a-ad7e-452c-98a8-da9d03634f14.png)

**Comment by moellep** [comment] 2022-04-21 21:22
I've reproduced this, it seems to be a corruption problem with flask and werkzeug. Flask is failing to find the static file entry point after the POST to /simulation-list responds with an srexception to force login:

```
"POST /simulation-list HTTP/1.1" 200 -
"{"simulationType":"elegant"}GET /static/html/login.html?20220421.171640 HTTP/1.1" 405 -
```

The problem does not occur with an earlier version of Werkzeug. I'd suggest fixing the flask and Werkzeug versions to 2.0.3

**Comment by robnagler** [comment] 2022-04-22 01:13
@moellep Would you fix them in sirepo/setup.py? thanks.

**Comment by moellep** [comment] 2022-04-22 20:24
I'm opening this issue again because I think it is worth getting to the bottom of the problem. We have seen corrupted servers prior on production prior to the 2.0.3 flask release, so I'm not confident that locking the version will fix those problems.

An addition note - when I debugged a bit more into werkzeug, the http request method is getting corrupted from "GET" to "{"SIMULATIONTYPE":"SRW"}GET" which seems to indicate our code could be clobbering something.

**Comment by robnagler** [comment] 2022-04-22 20:27
i'm almost tempted to say that we should focus on migrating to tornado...

**Comment by moellep** [comment] 2022-04-22 23:20
I tracked down the problem - it looks like when an exception is encountered before the full request has been read by flask, it stays around to the next request which corrupts the http request line for the next request.

For example, "POST /simulation-list" is sent with a payload of "{"simulationType":"srw"}", but an "unauthorized" SRException is thrown before the request can be handled.

The next request for "GET /static/html/login.html" is made by the client, but that old buffer is still unread, so flask reads the request line as "{"simulationType":"srw"}GET /static/html/login.html" and then can't figure out request method and raises a MethodNotAllowed.

Adding a flask.request.get_data() to sirepo's http_reply.py fixes the problem, but I think it should probably be somewhere earlier:

```python
def gen_exception(exc):
    """Generate from an Exception

    Args:
        exc (Exception): valid convert into a response
    """
    # If an exception occurs here, we'll fall through
    # to flask, which will have code to handle this case.

    # ensure all request data is read, or the next request may read it
    flask.request.get_data(cache=False),

    if isinstance(exc, sirepo.util.Reply):
        return _gen_exception_reply(exc)
    if isinstance(exc, werkzeug.exceptions.HTTPException):
        return _gen_exception_werkzeug(exc)
    return _gen_exception_error(exc)
```

**Comment by moellep** [comment] 2022-04-23 00:55
This is a know issue, which only happens on development servers:
https://github.com/pallets/werkzeug/issues/2380
Any posted data needs to get fully read by the server or it will carry over into the next keep-alive request.

**Comment by moellep** [comment] 2022-05-02 16:46
This has been fixed by flask by disabling keep-alive connections when running the http.server.

**Closed by moellep** 2022-05-02 16:46 UTC
Labels: test
