### ISSUE TITLE
SRW - duplicated simulation does not have predefined electron beams

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#795] opened 2017-06-23 01:56 UTC
Reported by @ochubar:
If a user copies a simulation and tries to view the list of predefined electron beams, the list appears to be empty.

Steps to reproduce (verified on beta server):
1) Open any simulation, e.g. Tabulated Undulator Example in the expert mode.
2) Click `Open as a New Copy` link in the cog-wheel.
3) In the new simulation check the electron beam parameters - it will be empty.
4) Change some parameters of the electron beam, e.g. switch `Drift Calculation Method` from automatic to manual and save the changes - the list of predefined electron beams will appear.

**Comment by robnagler** [comment] 2017-06-23 03:39
On alpha, I tried to rename the Custom Beam of the Tabulated Undulator Example, and there was a client error (below). I had no predefined beams so perhaps this is related or a red herring. 

```text
Application Error: TypeError: Cannot read property 'length' of undefined. A report was sent to the server.
```

```text
TypeError: Cannot read property 'length' of undefined
    at srw.js:1381
    at m.$broadcast (angular-1.6.1.min.js:150)
    at broadcastChanged (sirepo.js:141)
    at Object.self.saveChanges (sirepo.js:475)
    at m.$scope.saveChanges (sirepo-components.js:212)
    at fn (eval at compile (angular-1.6.1.min.js:237), <anonymous>:4:153)
    at e (angular-1.6.1.min.js:282)
    at m.$eval (angular-1.6.1.min.js:147)
    at m.$apply (angular-1.6.1.min.js:148)
    at HTMLButtonElement.<anonymous> (angular-1.6.1.min.js:282)
```

**Comment by mrakitin** [comment] 2017-06-23 13:47
I think the predefined beams should always exist, so this is also a problem to be addressed.

**Comment by moellep** [comment] 2017-08-01 19:56
I've reproduced this with a tabulated undulator example. The app is calling getApplicationData() with the method "model_list" for the list of electron beams and the undulator list. If the two calls happen quickly, the first is ignored by the getApplicationData() debouncer. The problem is the debouncer is depending on the method name to be unique. I've got a fix for this case.

**Closed** 2017-08-01 19:58 UTC
Labels: bug

**Comment by mrakitin** [comment] 2017-08-01 20:16
Thanks @moellep! This is an important fix.
