### ISSUE TITLE
Background _kill() causes repeated PMIX ERROR

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1350] opened 2018-09-17 17:10 UTC
On dev, if the client calls "run-cancel" then the server gets a PMIX error for all subsequent calls to run a simulation. To reproduce, open the "Two Poles" warpvnd simulation, change the Channel Width value and then immediately return to the simulation list page, which will call run-cancel on the field report.  Then return to the "Two Poles" simulation and all simulations should fail.

If the Background _kill() method is stubbed out, then other simulations are not affected.

```
../sirepo/server.py:799:_simulation_error error in read_result: /home/vagrant/src/radiasoft/sirepo/run/user/S0QmCORV/warpvnd/JYrnYMCG/f
ieldComparisonReport: error: ../sirepo/runner.py:327:_start S0QmCORV-JYrnYMCG-fieldComparisonReport: child will exec: ['sirepo', 'warpv
nd', 'run', '/home/vagrant/src/radiasoft/sirepo/run/user/S0QmCORV/warpvnd/JYrnYMCG/fieldComparisonReport']
[v.bivio.biz:27026] PMIX ERROR: NOT-FOUND in file src/client/pmix_client.c at line 205
```

**Comment by robnagler** [comment] 2018-09-17 18:27
Duplicate of #1323

**Closed by robnagler** 2018-09-17 18:27 UTC
