### ISSUE TITLE
Reorganize app directories on server

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#2719] opened 2020-07-31 15:20 UTC
I believe this has been discussed but not formalized: instead of all the e,g, sim_data files in one level, organize them by app to be sim_data/<app>/.

**Comment by robnagler** [comment] 2020-07-31 15:46
I think this is a duplicate of #1990. 


Again, there are some important reasons to put all apps in sim_data. You can look for `<root>.sim_data` to find all sim_data implementations. For example, you can say `sirepo` on the command line, and it will print out all modules in `sirepo.pkcli`. This is declarative: only modules that live in pkcli can be executed. Ditto for sim_data: only modules that are in the sim_data package can do things with sim_data.

One of the bugs we have with the template package is that everything got thrown in there as opposed to having the meaning that any module in template represents a code and therefore all valid code implementations live in template. Instead we have to denormalize that list in template.__init__, which creates a maintenance problem. You have to update template.__init___ when you add a new code.

For proprietary codes, which will be run from separate repos, we'll want to look for them, e.g. sirepoflash.template. This approach is practical, because you can search for all python packages named `sirepo<code>`.

Also `pkcli.<code>` should go away. These should not be pkcli, but dispatched from a common pkcli. There could be something like sirepo.sim_exec that would hold these modules and a pkcli called sim_exec.

**Closed** 2022-02-22 00:13 UTC
