### ISSUE TITLE
elegant: enable the duplication of reports

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#965] opened 2017-11-14 21:54 UTC
This should be useful for all Sirepo apps, but it is bothering me while I'm working with elegant.

When looking at particle or field data, it's very common that a scientist will want to see two (or more) projections side by side. For example, x vs px and y vs py are common choices that are viewed together.

At the moment, Sirepo requires that you look at one such plot, then overwrite the canvas with the other plot. This is frustrating.

It should be possible to duplicate any report, so that multiple projections of the same data can be viewed side by side.

**Comment by bruhwiler** [comment] 2018-05-26 21:06
This is equally important for the new Synergia app.
It's frustrating if you can't look at multiple "Bunch Reports" (soon to be renamed "Beam Phase Space" reports).

**Comment by bruhwiler** [comment] 2019-10-25 21:48
This feature is required for JSPEC, so the time can be billed to the MCOOL 2a project.
The implementation should be done in a way that is general across all apps.

**Comment by bruhwiler** [comment] 2020-02-10 20:47
@sjcrs -- please review this issue.
Is this a priority for JSPEC?

**Comment by sjcrs** [comment] 2020-02-11 16:35
Yes, this would be useful for JSPEC.
I can see a user creating a visualization, going back to source to switch one thing (Force model from drop-down, or B-field in float field, etc), then wanting to see how that change propagates back in the visualization tab. The user should be able to plot in a separate canvas for the 2-d histograms or overlaid for the line plots

**Comment by robnagler** [comment] 2022-02-21 18:38
Duplicate of #878

**Closed by robnagler** 2022-02-21 18:38 UTC
Labels: 2, customer
