### ISSUE TITLE
20221212 Fast clicking on Backtracking caused clientException

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5265] opened 2022-12-13 00:04 UTC
I was trying out alpha. Logged in to srw, went to elegant via the home page supported codes, and clicked on Examples then Backtracking pretty quickly. Got clientException. Nothing else in the server log. May not be worth debugging:

```txt
23:57:58 sirepo/server.py:157:api_errorLogging ip0: javascript error: {
23:57:58 "cause": "<no cause>",
23:57:58 "message": "Error: [$controller:ctrlreg] http://errors.angularjs.org/1.7.8/$controller/ctrlreg?p0=ElegantSourceController",
23:57:58 "stackTrace": "Error: [$controller:ctrlreg] http://errors.angularjs.org/1.7.8/$controller/ctrlreg?p0=ElegantSourceController
23:57:58 at https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:7:168
23:57:58 at https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:97:344
23:57:58 at ea (https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:79:334)
23:57:58 at p (https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:71:142)
23:57:58 at g (https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:64:477)
23:57:58 at g (https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:64:494)
23:57:58 at https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:64:100
23:57:58 at https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:69:418
23:57:58 at d (https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:66:223)
23:57:58 at m (https://alpha.sirepo.com/static/js/ext/angular.min.js?20221212.215514:70:442)",
23:57:58 "type": "clientException",
23:57:58 "url": "https://alpha.sirepo.com/elegant#/source/uh8tdPLf"
23:57:58 }
```

**Comment by moellep** [comment] 2023-01-03 00:00
The error is ```The controller with the name 'ElegantSourceController' is not registered.```
I can't reproduce the problem. I don't see how the simulation-list call was made before elegant.js was fully loaded.

**Comment by moellep** [comment] 2023-01-03 19:06
Reopening this - I encountered this immediately after a release. The simulations page was available, but clicking on an elegant simulation caused the ElegantSourceController missing error. 

The important part is at the top of the javascript console is the error:
```Uncaught SyntaxError: Unexpected token '<'.  sirepo-lattice.js: 1```

So the javascript received a bad file and angular did not get to initialize fully after that point.

The server side shows a return code and length of "200 139" and the 139 isn't the correct size for that file. I'm guessing it was returning an html error message.

**Comment by moellep** [comment] 2023-01-03 19:15
I noticed vtk.js also failed to load correctly for me with the same "200 139" status/length and that caused the SRW 3d report to fail. Also, several beamline icons were not displaying. I'm guessing that one of the server instances was not working correctly.

**Comment by moellep** [comment] 2023-01-03 19:22
Control-clicking on the reload button in Chrome and selecting "Empty cache and hard reload" reproduces the problem on the SRW beamline tab. Random requests will fail with "200 0", for example grating.svg and then the grating element doesn't appear in the beamline toolbar.

**Comment by robnagler** [comment] 2023-01-04 01:28
My approach to this will be to deploy tornado. I'm pretty close. I think this must be something with flask and threading...

**Comment by moellep** [comment] 2023-01-04 21:32
The solution in the meantime is to restart nginx and then resetart sirepo.

**Comment by moellep** [comment] 2023-02-16 21:27
This is duplicate of #5016

**Closed by moellep** 2023-02-16 21:27 UTC
Labels: elegant
