### ISSUE TITLE
Radia: Enable parallel computation in Sirepo Application

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#3374] opened 2021-03-03 01:40 UTC
We'd like to take advantage of the MPI parallelization of the interaction matrix calculation as well as the field calculation. Whatever number of cores are available for the Sirepo user should be able to be used in the parallel computation.
We will want to also be able to run on external clusters such as NERSC, but that would be a Phase IIa task.

**Comment by mkeilman** [comment] 2021-03-09 17:02
Duplicate of #2347

**Closed by mkeilman** 2021-03-09 17:02 UTC
