### ISSUE TITLE
elegant:  problem with overly reccursive beamlines

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1031] opened 2018-01-17 21:19 UTC
Suppose beamline 'bl' includes beamline 'linac1'.
It's possible to add 'bl' to the sequence of elements in 'linac1'.
This provokes an elegant error that the beamline is overly recursive.

The GUI should not allow the user to make this change in the first place.

**Comment by moellep** [comment] 2018-01-17 21:33
Duplicate of #999

**Closed by moellep** 2018-01-17 21:33 UTC
