### ISSUE TITLE
Lattice tab in Elegant does not work properly on iPad

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#778] opened 2017-06-20 21:11 UTC
Chris and I were working through the demo for the Elegant work, and we found that the second column of the Lattice tab only appears in portrait mode on our demo iPad.

**Comment by robnagler** [comment] 2017-06-20 21:58
Did you mean the column disappears in portrait mode?

**Comment by sdwebb** [comment] 2017-06-21 06:03
Sorry, yes, the column disappears in portrait mode and only appears in landscape mode.

**Comment by robnagler** [comment] 2017-06-21 14:55
The problem is that there isn't enough real estate to reasonably drag-n-drop in portrait mode. You have to have both the Beamlines and Elements visible in order for the editor to be useful. We made the decision in narrow screens to have the editor in a read-only mode. You can look at the beamline, but you can't edit it. 

While it is great to have an iPad version of Sirepo, it's more of a demo tool than something that's actually going to be used for science. The purpose of the iPad is to demo enough stuff to get people interested to try out Sirepo on their desktops. Therefore, I would argue that this particular situation should be avoided in demos. Hold the iPad in landscape when you want to edit. :)

**Comment by robnagler** [comment] 2017-07-03 22:29
@sdwebb Can I close this?

**Closed** 2017-08-01 21:19 UTC
Labels: 1st Priority
