### ISSUE TITLE
oauth - error when logging in in several browsers simultaneously

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#753] opened 2017-05-26 15:25 UTC
An attempt to log in using GitHub credentials on two separate browsers results in a bad gateway error in the second browser, and there is the following error message in the server's log:
```py
/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/uri_router.py:174:_dispatch oauth-authorized/github: error: KeyError:
'oauth_nonce'
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/server.py", line 714, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/server.py", line 348, in api_oauthAuthorized
    return oauth.authorized_callback(app, oauth_type)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/oauth.py", line 70, in authorized_callback
    state = _remove_session_key('oauth_nonce')
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/oauth.py", line 144, in _remove_session_key
    value = flask.session[name]
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/session.py", line 754, in __getitem__
    return self._session()[key]
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/server.py", line 714, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/server.py", line 348, in api_oauthAuthorized
    return oauth.authorized_callback(app, oauth_type)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/oauth.py", line 70, in authorized_callback
    state = _remove_session_key('oauth_nonce')
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170503.175512-py2.7.egg/sirepo/oauth.py", line 144, in _remove_session_key
    value = flask.session[name]
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/session.py", line 754, in __getitem__
    return self._session()[key]
KeyError: 'oauth_nonce'
```
When the second browser is restarted, the user becomes authenticated.

**Comment by robnagler** [comment] 2017-05-26 16:49
I can't reproduce. Questions may help:

* Was the second browser logged in before?

**Comment by mrakitin** [comment] 2017-05-27 02:05
Hi Rob,

- The second browser was not logged in before, it stayed on some simulation page, and then then, after the first browser was successfully logged in, an attempt was made to log in the second browser (MS Edge).
- Yes, the browser was closed completely, and then started again, but after the restart the logged in user icon appeared in the interface.

I believe it's hard to reproduce, I never met this problem myself. Let's try different scenarios. Maybe it's worth to remove any authenticated apps from a GitHub account, and try to do it again? Oleg tried it for the first time...

Thanks,
Maksim

**Comment by robnagler** [comment] 2017-05-27 19:23
Still not exactly clear. Are we talking about two different browser vendors, e.g. MS Edge and Chrome? Or are they both Edge. In the latter case, it's clear what's going on. In the former, not sure.

**Comment by mrakitin** [comment] 2017-05-27 19:39
It's two different browser vendors - Chrome and MS Edge.

**Comment by robnagler** [comment] 2017-05-29 20:47
I created two new anonymous users on Chrome & Safari on my Mac. Then I logged them in almost simultaneously via GitHub with an unbound user. Worked fine.

There is no error handling in the client for multiple windows (same browser) logging in simultaneously. The oauth_nonce error would come about if two windows from the same browser (same flask session) were logging in exactly the same time.

I can reproduce a similar error by double clicking (with command key to pop up two new windows):

```
May 29 20:22:17  2657 51018 /home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170420.154759-py2.7.egg/sirepo/oauth.py:72:authorized_callback mismatch oauth state: hByoIa90bTCR148vOs9zyu8UapCGXUadSOT636LiiFy4QrFsbEsdN0Hm4nEb4uRW != ZPFFbJ57CzjONqgM0joPq7nobFc2Z1lOZ9Gkyv5WPcshcPcPDzyazzkGdbpXbcBb
May 29 20:22:17  2657 51018 /home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170420.154759-py2.7.egg/sirepo/uri_router.py:174:_dispatch oauth-authorized/github: error: Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170420.154759-py2.7.egg/sirepo/server.py", line 714, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170420.154759-py2.7.egg/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170420.154759-py2.7.egg/sirepo/server.py", line 348, in api_oauthAuthorized
    return oauth.authorized_callback(app, oauth_type)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170420.154759-py2.7.egg/sirepo/oauth.py", line 73, in authorized_callback
    werkzeug.exceptions.abort(403)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
```

I looked in the logs, and the error does appear once on 30/Mar/2017:14:22:03 on beta. It looks like there's an out of order event:

```
[30/Mar/2017:14:22:03 +0000] "GET /login/elegant/github?next=/simulations
[30/Mar/2017:14:21:16 +0000] "POST /simulation-list
Mar 30 14:22:17 oauth-authorized/github: error: KeyError: 'oauth_nonce'
[30/Mar/2017:14:22:17 +0000] "GET /oauth-authorized/github?code=9
[30/Mar/2017:14:22:17 +0000] "GET /favicon.ico
[30/Mar/2017:14:22:21 +0000] "GET /elegant
```

Note the POST to /simulation-list was started on 14:21:16 but didn't complete until after 14:22:03 (and before 14:22:17). This implies (although not sure) that the user clicked on simulation list and then many clicked on login. The two requests finished near simultaneously.

The exception does not invalidate the login session (probably should) so when the browser is refreshed GitHub and Sirepo are happy. There's no way to signal to the GitHub callback that actually, well, this wasn't the right nonce (I'm guessing). It's our side that has to invalidate the session in this case.

I don't think we can debug this without more examples. I will create an issue to cleanup the nonce handling.

**Comment by mrakitin** [comment] 2017-05-29 21:58
Thanks Rob.

**Comment by robnagler** [comment] 2017-06-17 14:19
We can't debug this so I'm closing.

**Comment by mrakitin** [comment] 2017-06-21 22:31
Rob, I was able to reproduce it on my system with clean run dir. I used 4 different browsers trying to log in to using my GitHub account, and it failed on the last two - MS IE and Edge. Why cannot we debug?

**Comment by robnagler** [comment] 2017-06-21 23:51
We'd better be clear about which bug we are debugging. The problem Oleg had was different than I was able to reproduce. Were you able to reproduce Oleg's error? Or did you reproduce the error I included the stack trace for?

**Comment by mrakitin** [comment] 2017-06-22 13:45
I think I reproduced Oleg's bug. The steps are:

0) In dev mode stop all Sirepo services, remove `run/` directory of Sirepo, and start all Sirepo services back. 
1) Open Firefox and log in with GitHub credentials.
2) Open Google Chrome and log in with GitHub credentials.
3) Open Internet Explorer and log in with GitHub credentials - the error appears in the server log and the browser continues to stay on the page for GitHub authentication.
4) Repeat the step 3 for MS Edge, the result is the same.

**Comment by robnagler** [comment] 2017-06-22 13:50
This might be a IE/Edge problem. I'll try to reproduce in Windows.

**Comment by mrakitin** [comment] 2017-06-22 14:00
Thanks Rob.

**Comment by bruhwiler** [comment] 2017-08-10 23:59
Is it important to understand and resolve this problem?
It seems to me like an artificial situation which will not be experienced by regular users.

**Comment by mrakitin** [comment] 2017-08-11 00:12
We can have it with low priority. Oleg and I met this situation with MS IE/Edge.

**Comment by robnagler** [comment] 2019-01-14 21:01
@mrakitin @ochubar is this still a problem

**Closed** 2019-10-01 22:42 UTC
Labels: 2, bug
