### ISSUE TITLE
SRW - wrong distance in the title of Partially Coherent Intensity Report

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#774] opened 2017-06-19 20:14 UTC
Reported by the CHX beamline scientist:
When a user performs a partially-coherent simulation of SRW in Sirepo, then stops it and changes the position of the last watchpoint, after clicking the "Save" button a title of the Partially Coherent Intensity Report changes showing the new distance, but the simulation wasn't done for the new distance. It's a bit confusing and dangerous since the user may have an impression that the simulation is done for the new distance, especially when several similar simulations are running at the same time. We need to update the distance only in case when the simulation was started.

**Comment by robnagler** [comment] 2017-06-20 13:47
I think if you update the report parameters, the report should be cleared until a new simulation is run. By default this happens automatically on the foreground reports. We can either close the report or make the report say "unavailable". 

This is a duplicate of #355, but I'll leave open as it was reported by a user

**Comment by mrakitin** [comment] 2017-06-20 15:17
Thanks Rob. I agree with the plan.

**Closed** 2017-10-31 22:52 UTC
Labels: 1st Priority, bug
