### ISSUE TITLE
backtracking

### ISSUE THREAD

**Issue by ypark39** [radiasoft/sirepo#1819] opened 2019-08-15 17:11 UTC
When the length is negative, the element image breaks. The image below should show four elements. 
![image](https://user-images.githubusercontent.com/30848452/63112361-e7412b80-bf44-11e9-920b-b106e06a25f3.png)

**Comment by moellep** [comment] 2019-08-16 19:57
I've reproduced the problem with this simulation:

https://beta.sirepo.com/elegant#/visualization/zbbYmnvS

I was curious how elegant would track the path, and it shows the flat magnet layout as 4 sequential bends. Sirepo should be fixed so the UI matches the floor coordinates.

![Screen Shot 2019-08-16 at 1 55 56 PM](https://user-images.githubusercontent.com/6516910/63194567-96f1c880-c02d-11e9-9038-cb7117c91d45.png)

**Comment by moellep** [comment] 2019-11-04 17:18
This is fixed with changes to #1882 and will be available on alpha.sirepo.com soon.

The beamline above now renders as:
![Lattice-BL1-13](https://user-images.githubusercontent.com/6516910/68142062-f902f100-feeb-11e9-8e3d-914fc73b6671.png)

Another example of a manually entered backtracking lattice.
Forward:
![Lattice-BL1-14](https://user-images.githubusercontent.com/6516910/68142108-159f2900-feec-11e9-90d3-8a02e3f3e31f.png)

Backward:
![Lattice-BLBack-1](https://user-images.githubusercontent.com/6516910/68142114-19cb4680-feec-11e9-9113-c6b27ef07d62.png)

Entering the backward lattice is no longer required because a new feature was added to the Simulation Status panel on the Visualization page, allowing backtracking. Selecting this item will automatically reverse the length and angle on all items and reverse the beamline order in the generated elegant lattice.
![Screen Shot 2019-11-04 at 10 13 45 AM](https://user-images.githubusercontent.com/6516910/68142220-4aab7b80-feec-11e9-91dd-0268eeb50366.png)

**Comment by bruhwiler** [comment] 2019-11-04 17:22
Given that backtracking is now indicated through a switch in the 'Simulation Status' report, I don't understand why you are changing how the beamline elements are rendered. I suggest you leave the rendering unchanged.

**Comment by moellep** [comment] 2019-11-04 17:36
The rendering was fixed for backtracking beamlines which were entered manually - for example, entering a beamline with all negative lengths. Previously the SVG rendering didn't show those beamlines correctly.

When you select the "Backtracking" toggle, the beamline appears unchanged on the lattice page.

**Comment by moellep** [comment] 2019-11-05 17:19
This feature now on alpha.sirepo.com, but is not quite correct - it needs to reverse the sign on the RFCA volt parameter for the backtracking case. This probably affects other elegant elements as well.

**Comment by robnagler** [comment] 2019-12-09 18:20
Marking as complete because waiting for prod.

**Closed by robnagler** 2019-12-09 18:20 UTC
Labels: customer
