### ISSUE TITLE
SRW: implement Detector element

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1184] opened 2018-05-03 00:50 UTC
Related code: https://github.com/ochubar/SRW/blob/b867750cdf2e49c74677f2fe457ad1ab43f9cbea/env/work/srw_python/srwl_bl.py#L731-L762

An example to be provided by @ochubar.

**Comment by robnagler** [comment] 2022-02-21 20:29
Duplicate of #839

**Closed by robnagler** 2022-02-21 20:29 UTC
