### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by klekomtsev** [radiasoft/sirepo#1028] opened 2018-01-17 20:53 UTC
Application Error: RangeError: Maximum call stack size exceeded. A report was sent to the server.

https://uspas-sirepo.radiasoft.org/elegant#/lattice/TtF6x17h

**Comment by robnagler** [comment] 2018-01-17 20:57
Thanks @klekomtsev we see the stack trace in the logs:

```text
```text
Jan 17 20:52:18   212 65159 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py:184:api_errorLogging 216.54.110.228: javascript error: {
    "cause": "Possibly unhandled rejection: {}",
    "message": "RangeError: Maximum call stack size exceeded",
    "stackTrace": [
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2791:34",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25",
        "explodeItems@https://uspas-sirepo.radiasoft.org/static/js/elegant.js?20180110.000000:2802:25"
    ],
    "type": "clientException",
    "url": "https://uspas-sirepo.radiasoft.org/elegant#/lattice/TtF6x17h"
}
216.54.110.228 - li-hs9rL998 [17/Jan/2018:20:52:18 +0000] "POST /error-logging HTTP/1.1" 200 86 "https://uspas-sirepo.radiasoft.org/elegant" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
```

**Comment by moellep** [comment] 2018-01-17 21:32
Duplicate of #999

**Closed by moellep** 2018-01-17 21:32 UTC
